mongo-db:
    image: mongo:latest
    command: "--smallfiles"

backend:
    build: .
    ports:
        - "33333:8080"
    environment:
        - PIAZZA_HOST=0.0.0.0
        - PIAZZA_SECRET=abc
    links:
        - mongo-db:mongo-db
