mongo-db:
    image: mongo:latest
    volumes:
        - './data:/data/db'
    command: "--smallfiles"

backend:
    build: .
    ports:
        - "33333:80"
    environment:
        - PIAZZA_HOST=0.0.0.0
        - PIAZZA_SECRET=abc
    links:
        - mongo-db:mongo-db
