mongo-db:
    image: mongo:latest
    volumes:
        - './data:/data/db'
    command: "--smallfiles"

backend:
    build: .
    ports:
        - "80:8080"
    environment:
        - PIAZZA_HOST=0.0.0.0
        - PIAZZA_SECRET=kFjJDFtc73gc87TD73gi8z29DZ
    links:
        - mongo-db:mongo-db
