mongo-db:
    image: mongo:latest
    volumes:
        - './data:/data/db'
    command: "--smallfiles"

backend:
    build: .
    ports:
        - "80:8080"
    volumes:
        - './logs:/logs'
    links:
        - mongo-db:mongo-db